const assert = require('node:assert/strict');
const {getConfig} = require('../js/self-defaults.js');
const {generate} = require('../js/passage-self-logic.js');
const config = getConfig();
assert.equal(config.classes.length, 32);
assert.equal(new Set(config.classes.map(c=>c.name)).size, 32);
assert.deepEqual(new Set(Object.keys(config.settings)), new Set(config.classes.map(c=>c.name)));
assert.ok(config.classes.some(c=>c.name==='4°1 Physique'));
assert.ok(!config.classes.some(c=>c.name==='4°2 Ang LV1'));
assert.deepEqual(config.settings['5°1 CHAM'].MARDI.A, {});
assert.equal(config.settings['5°3'].LUNDI.B.fin, '11h05');
assert.equal(config.settings['6°1'].VENDREDI.A.reprise, '13h55');
const result=generate({...config,day:'LUNDI',weekType:'B',weekNumber:1});
assert.ok(result[0].classes.includes('5°3'));
assert.ok(result[1].classes.includes('4°1 Physique'));
config.classes.pop(); config.settings['5°3'].LUNDI.B.fin='12h00';
assert.equal(getConfig().classes.length,32);
assert.equal(getConfig().settings['5°3'].LUNDI.B.fin,'11h05');
if(process.argv[2]) assert.deepEqual(getConfig(),JSON.parse(require('node:fs').readFileSync(process.argv[2],'utf8')));
console.log('Self defaults: classes, groups, exact times, independent copies and supplied configuration validated.');
